"""Configurable file paths for IFG used in the source files and script files."""

from pathlib import Path

##### Target Molecular SMILES Codes #####
STRUCTURES_PATH = Path("resources") / 'smiles.txt'
"""The path to a file with a list of hydrogen-suppressed organic molecule SMILES codes to process in the main.py script"""

##### Target Functional Groups #####
FUNCTIONAL_GROUPS_PATH = Path("resources") / 'FGlist.txt'
"""The path to a file with the list of identifiable functional group SMILES codes"""

##### Target Main Output Excel Sheet #####
MAIN_OUTPUT_PATH = Path("output") / 'ref_test.xlsx'
"""The path to the excel file generated by the main.py script"""

##### Target Analysis Output Excel Sheet #####
ANALYSIS_OUTPUT_PATH = Path("output") / 'stats2.xlsx'
"""The path to the excel file generated by the analysis.py script"""

##### Target Structure Bandgaps Input Excel Sheet #####
BANDGAPS_PATH = Path("resources") / 'CrystalData.xlsx'
"""The path to the excel file with the bandgaps used by the analysis.py script"""